[package]
name = "aws-lc"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
aws-lc-rs = { version = "1.12.2", features = ["fips", "bindgen"] }

[build-dependencies]
cbindgen = "0.28.0"

[profile.dev]
incremental=true