#ifndef aws_lc_h
#define aws_lc_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace aws_lc {

enum class CHmacAlgorithm {
  SHA256,
  SHA384,
  SHA512,
};

enum class CHmacError {
  Ok,
  InvalidKey,
  InvalidAlgorithm,
  InvalidInput,
  InvalidOutput,
  CryptoError,
};

extern "C" {

const int8_t *get_error();

CHmacError generate_hmac_key(CHmacAlgorithm algorithm, void **key_handle, char **err);

CHmacError hmac_sign(void *key_handle,
                     const uint8_t *data,
                     uintptr_t data_len,
                     uint8_t *output,
                     uintptr_t *output_len,
                     const char **err);

CHmacError hmac_verify(void *key_handle,
                       const uint8_t *data,
                       uintptr_t data_len,
                       const uint8_t *tag,
                       uintptr_t tag_len);

void hmac_destroy(void *key_handle);

}  // extern "C"

}  // namespace aws_lc

#endif  // aws_lc_h
