#ifndef aws_lc_h
#define aws_lc_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace aws_lc {

extern "C" {

int32_t generate_hmac_sha256_key(void **key_ptr);

void retake_key(void *raw_ptr);

}  // extern "C"

}  // namespace aws_lc

#endif  // aws_lc_h
