#ifndef aws_lc_h
#define aws_lc_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace aws_lc {

enum class CHmacError {
  Ok,
  InvalidKey,
  InvalidAlgorithm,
  InvalidInput,
  InvalidOutput,
  CryptoError,
};

enum class CHmacAlgorithm {
  SHA256,
  SHA384,
  SHA512,
};

enum class RsaError {
  Ok,
  InvalidKeySize,
  InvalidInput,
  InvalidOutput,
  CryptoError,
  InvalidKey,
};

enum class RsaKeySize {
  Rsa2048,
  Rsa3072,
  Rsa4096,
  Rsa8192,
};

enum class RsaOaepEncryptionAlgorithm {
  OaepSha1Mgf1Sha1,
  OaepSha256Mgf1Sha256,
  OaepSha384Mgf1Sha384,
  OaepSha512Mgf1Sha512,
};

extern "C" {

void init_lib();

const int8_t *get_error();

/// # Safety
/// All pointers should be valid
CHmacError generate_hmac_key(CHmacAlgorithm algorithm, void **key_handle, char **err);

/// # Safety
/// All pointers should be valid
CHmacError hmac_sign(void *key_handle,
                     const uint8_t *data,
                     uintptr_t data_len,
                     uint8_t *output,
                     uintptr_t *output_len,
                     const char **err);

/// # Safety
/// All pointers should be valid
CHmacError hmac_verify(void *key_handle,
                       const uint8_t *data,
                       uintptr_t data_len,
                       const uint8_t *tag,
                       uintptr_t tag_len);

void hmac_destroy(void *key_handle);

RsaError generate_rsa_private_key(RsaKeySize key_size, void **key_handle, const char **err);

RsaError rsa_private_key_to_DER_PKCS8_bytes(void *private_key_handle,
                                            uint8_t *output,
                                            uintptr_t *output_len,
                                            const char **err);

RsaError rsa_private_key_from_DER_PKCS8_bytes(const uint8_t *private_key,
                                              uintptr_t private_key_len,
                                              void **private_key_handle,
                                              const char **err);

RsaError rsa_public_key_to_DER_X509_bytes(void *public_key_handle,
                                          uint8_t *output,
                                          uintptr_t *output_len,
                                          const char **err);

RsaError rsa_public_key_from_DER_X509_bytes(const uint8_t *public_key,
                                            uintptr_t public_key_len,
                                            void **public_key_handle,
                                            const char **err);

RsaError generate_rsa_public_key(void *private_key_handle,
                                 void **public_key_handle,
                                 const char **err);

RsaError generate_rsa_oaep_key(void *public_key_handle,
                               void **public_oaep_key_handle,
                               uintptr_t *output_len,
                               const char **err);

RsaError encrypt_with_rsa_oaep_key(RsaOaepEncryptionAlgorithm algorithm,
                                   void *oaep_public_key_handle,
                                   const uint8_t *plaintext,
                                   uintptr_t plaintext_len,
                                   uint8_t *output,
                                   uintptr_t *output_len,
                                   const char **err);

RsaError rsa_oaep_decrypt(RsaOaepEncryptionAlgorithm algorithm,
                          void *private_key_handle,
                          const uint8_t *ciphertext,
                          uintptr_t ciphertext_len,
                          uint8_t *output,
                          uintptr_t *output_len,
                          const char **err);

}  // extern "C"

}  // namespace aws_lc

#endif  // aws_lc_h
